name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./

      - name: Show
        env:
          IDENTIFIER: ${{ steps.exercise.outputs.identifier }}
        run: |
          set -x
          echo "IDENTIFIER=${IDENTIFIER}"

      - name: Verify
        env:
          IDENTIFIER: ${{ steps.exercise.outputs.identifier }}
        run: |
          set -x
          [[ "${IDENTIFIER}" =~ .*"$(date '+%Y%m%d')".* ]]
          [[ "${IDENTIFIER}" =~ .*"${GITHUB_JOB}".* ]]
          [[ "${IDENTIFIER}" =~ .*"${GITHUB_RUN_ID}".* ]]
          [[ "${IDENTIFIER}" =~ .*"${GITHUB_RUN_ATTEMPT}".* ]]
          [[ "${IDENTIFIER}" =~ .*"${GITHUB_SHA}".* ]]
          [[ "${IDENTIFIER}" =~ .*"${GITHUB_ACTOR_ID}".* ]]
